title: Amulya Gowri Jagadeesh
# author: Amulya
email: amulyagowrij@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Amulya Gowri J Summary Text.
  
linkedin_username: amulyagowrij

show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
